```{r}
library(tidyverse)
library(RSelenium)
library(netstat)
library(webdriver)
```


```{r}

TwitchTrackerLinks = read.csv(file = "C:/Users/15153/Desktop/TwitchUsernameTrackerLink.csv")

AgentFinalList = read.csv(file = "C:/Users/15153/Desktop/FinalAgentList.csv", header = TRUE)
MapList = read.csv(file = "C:/Users/15153/Desktop/MapList.csv",header = TRUE)
AgentMapList = read.csv(file = "C:/Users/15153/Desktop/AgentMapComboList.csv", header = TRUE)
AgentMapList$WinPct = 0
AgentMapList$Matches = 0

agentLinkList = data.frame(matrix(ncol = 3, nrow = 1))
names(agentLinkList) = c("Jett","Kayo","Chamber")
agentLinkList$Jett = "https://titles.trackercdn.com/valorant-api/agents/add6443a-41bd-e414-f6ad-e58d267f4e95/displayicon.png"
agentLinkList$Kayo = "https://titles.trackercdn.com/valorant-api/agents/601dbbe7-43ce-be57-2a40-4abd24953621/displayicon.png"
agentLinkList$Chamber = "https://titles.trackercdn.com/valorant-api/agents/22697a3d-45bf-8dd7-4fec-84a9e28c69d7/displayicon.png"
agentLinkList$Astra = "https://titles.trackercdn.com/valorant-api/agents/41fb69c1-4189-7b37-f117-bcaf1e96f1bf/displayicon.png"
agentLinkList$Breach = "https://titles.trackercdn.com/valorant-api/agents/5f8d3a7f-467b-97f3-062c-13acf203c006/displayicon.png"
agentLinkList$Brimstone = "https://titles.trackercdn.com/valorant-api/agents/9f0d8ba9-4140-b941-57d3-a7ad57c6b417/displayicon.png"
agentLinkList$Cypher = "https://titles.trackercdn.com/valorant-api/agents/117ed9e3-49f3-6512-3ccf-0cada7e3823b/displayicon.png"
agentLinkList$Fade = "https://titles.trackercdn.com/valorant-api/agents/dade69b4-4f5a-8528-247b-219e5a1facd6/displayicon.png"
agentLinkList$Killjoy = "https://titles.trackercdn.com/valorant-api/agents/1e58de9c-4950-5125-93e9-a0aee9f98746/displayicon.png"
agentLinkList$Neon = "https://titles.trackercdn.com/valorant-api/agents/bb2a4828-46eb-8cd1-e765-15848195d751/displayicon.png"
agentLinkList$Omen = "https://titles.trackercdn.com/valorant-api/agents/8e253930-4c05-31dd-1b6c-968525494517/displayicon.png"
agentLinkList$Phoenix = "https://titles.trackercdn.com/valorant-api/agents/eb93336a-449b-9c1b-0a54-a891f7921d69/displayicon.png"
agentLinkList$Raze = "https://titles.trackercdn.com/valorant-api/agents/f94c3b30-42be-e959-889c-5aa313dba261/displayicon.png"
agentLinkList$Reyna = "https://titles.trackercdn.com/valorant-api/agents/a3bfb853-43b2-7238-a4f1-ad90e9e46bcc/displayicon.png"
agentLinkList$Sage = "https://titles.trackercdn.com/valorant-api/agents/569fdd95-4d10-43ab-ca70-79becc718b46/displayicon.png"
agentLinkList$Skye = "https://titles.trackercdn.com/valorant-api/agents/6f2a04ca-43e0-be17-7f36-b3908627744d/displayicon.png"
agentLinkList$Sova = "https://titles.trackercdn.com/valorant-api/agents/320b2a48-4d9b-a075-30f1-1f93a9b638fa/displayicon.png"
agentLinkList$Viper = "https://titles.trackercdn.com/valorant-api/agents/707eab51-4836-f488-046a-cda6bf494859/displayicon.png"
agentLinkList$Yoru = "https://titles.trackercdn.com/valorant-api/agents/7f94d92c-4234-0a36-9646-3a87eb8b5c89/displayicon.png"
```


```{r}

```


```{r}

generateData = function(trackerLink) {
  
  remDr$navigate(trackerLink)
  Sys.sleep(5)

#Get 220 matches loaded on page
for(i in 1:10) {
  morebutton = remDr$findElement(using = 'xpath', '//button[contains(text(), "Load More Matches")]')
morebutton$clickElement()
Sys.sleep(5)
}

#Find Maps
maps = remDr$findElements(using = 'class name', 'match__name')
map_names = lapply(maps, function (x) x$getElementText()) %>% unlist()


#Find Agents
agents = remDr$findElements(using = 'xpath', "//div[@class = 'match__portrait']//img")
agent_names = lapply(agents, function (x) x$getElementAttribute('src')) %>% unlist()


#Find Score (to calculate if win/lose/draw)
scoreWon = remDr$findElements(using = 'class name', 'score--won')
scoreWonList = lapply(scoreWon, function (x) x$getElementText()) %>% unlist()


scoreLost = remDr$findElements(using = 'class name', 'score--lost')
scoreLostList = lapply(scoreLost, function (x) x$getElementText()) %>% unlist()

#Grab Player Username
player = remDr$findElement(using = 'class name', 'trn-ign__username')
playerName = player$getElementText() %>% unlist()

#Win/Lose
scoreLostList2 = as.data.frame(scoreLostList)
scoreWonList2 = as.data.frame(scoreWonList)

df = cbind(scoreWonList2, scoreLostList2)
df$scoreWonList = as.numeric(scoreWonList)
df$scoreLostList = as.numeric(scoreLostList)

for(x in 1:length(scoreWonList)) {
  df$WinorLose[x] = ifelse(df$scoreWonList[x] > df$scoreLostList[x], "Win", "Lose")
  if(df$scoreWonList[x] == df$scoreLostList[x]) {
    df$WinorLose[x] == "Draw"
  }
}
 
#Agents
agent_names2 = as.data.frame(agent_names)

for(x in 1:length(agent_names)) {
  if(identical(agent_names2$agent_names[x],agentLinkList$Jett)) {
    agent_names2$agent_names[x] = "Jett"
  }
 if(identical(agent_names2$agent_names[x],agentLinkList$Chamber)) {
    agent_names2$agent_names[x] = "Chamber"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Astra)) {
    agent_names2$agent_names[x] = "Astra"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Breach)) {
    agent_names2$agent_names[x] = "Breach"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Brimstone)) {
    agent_names2$agent_names[x] = "Brimstone"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Cypher)) {
    agent_names2$agent_names[x] = "Cypher"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Fade)) {
    agent_names2$agent_names[x] = "Fade"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Killjoy)) {
    agent_names2$agent_names[x] = "Killjoy"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Neon)) {
    agent_names2$agent_names[x] = "Neon"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Omen)) {
    agent_names2$agent_names[x] = "Omen"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Phoenix)) {
    agent_names2$agent_names[x] = "Phoenix"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Raze)) {
    agent_names2$agent_names[x] = "Raze"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Reyna)) {
    agent_names2$agent_names[x] = "Reyna"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Sage)) {
    agent_names2$agent_names[x] = "Sage"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Skye)) {
    agent_names2$agent_names[x] = "Skye"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Sova)) {
    agent_names2$agent_names[x] = "Sova"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Viper)) {
    agent_names2$agent_names[x] = "Viper"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Yoru)) {
    agent_names2$agent_names[x] = "Yoru"
  }
   if(identical(agent_names2$agent_names[x],agentLinkList$Kayo)) {
    agent_names2$agent_names[x] = "Kayo"
   }
}

#Maps
map_list = as.data.frame(map_names)

WinLose = as.data.frame(df$WinorLose)


#Final Put Together
Output = cbind(playerName,WinLose,agent_names2,map_list)
colnames(Output)[2] = "WinorLose"

Output = Output[which(Output$WinorLose == "Win" | Output$WinorLose == "Lose"),]

for(i in 1:dim(AgentFinalList)[1]) {
agentIndex = which(Output$agent_names == AgentFinalList[i,]) # Take indexes for each game for each agent
  #Check that this length is more than 0 before doing any more processsing

if (length(agentIndex != 0)) {
  for(j in 1:dim(MapList)[1]) {
    map_index = which(Output$map_names == MapList[j,])
    
    combinedIndex = intersect(map_index,agentIndex)
    if(length(combinedIndex != 0) && length(which(Output[combinedIndex,]$WinorLose == "Win")) != 0) {
    WinPct = length(which(Output[combinedIndex,]$WinorLose == "Win")) / length(combinedIndex)
    AgentMapIndex = which(AgentMapList$Agent == AgentFinalList[i,] & AgentMapList$Map == MapList[j,])
    AgentMapList[AgentMapIndex,]$WinPct = WinPct
    AgentMapList[AgentMapIndex,]$Matches = length(combinedIndex)
    }
    else if(length(combinedIndex != 0) && length(which(Output[combinedIndex,]$WinorLose == "Win")) == 0) {
      AgentMapIndex = which(AgentMapList$Agent == AgentFinalList[i,] & AgentMapList$Map == MapList[j,])
      AgentMapList[AgentMapIndex,]$Matches = length(combinedIndex)
    }
  }
  }
}
AgentMapList = cbind(playerName,AgentMapList)
return(AgentMapList)
}



```

```{r}

rs_driver_object = RSelenium::rsDriver(browser =  "chrome", chromever = "101.0.4951.41", port = free_port())
remDr = rs_driver_object$client
rs_driver_object$client$close()
remDr$open()

for(i in 1:nrow(TwitchTrackerLinks)) {                  
write.csv(generateData(TwitchTrackerLinks$TrackerLink[i]), paste0("C:/Users/15153/Desktop/Data/",TwitchTrackerLinks$TwitchName[i], ".csv"))
}

remDr$close()
```

